name: Tests

on:
  workflow_dispatch:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests
        run: python -m pytest api_tests/
        env:
          INGRESS_URL: ${{ secrets.INGRESS_URL }}

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests
        run: python -m pytest web_tests/
        env:
          INGRESS_URL: ${{ secrets.INGRESS_URL }}
